# Generated by Django 5.2 on 2025-04-26 11:12

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("books", "0004_book_description_book_isbn"),
    ]

    operations = [
        migrations.AddField(
            model_name="book",
            name="copies",
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name="book",
            name="total_copies",
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name="reservation",
            name="reserved_date",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
