# Generated by Django 5.2 on 2025-04-27 01:25

from django.db import migrations, models


class Migration(migrations.Migration):



    operations = [
        migrations.AlterField(
            model_name="reservation",
            name="collecting_week",
            field=models.DateField(),
        ),
    ]
