# Generated by Django 5.2 on 2025-04-27 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("books", "0010_alter_reservation_collecting_week"),
    ]

    operations = [
        migrations.AlterField(
            model_name="reservation",
            name="collecting_week",
            field=models.DateField(blank=True, null=True),
        ),
    ]
