# Generated by Django 5.2 on 2025-04-27 02:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("books", "0011_alter_reservation_collecting_week"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="reservation",
            name="collecting_week",
        ),
    ]
